[package]
name = "tada"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
chumsky = "0.8.0"
clap = { version = "4.0.26", features = ["derive", "deprecated"] }
pretty = "0.11.3"
tempfile = "3.3.0"
